import type { EngineKey } from "../runtime/engineRegistry.js";

export type SlashEngine = EngineKey;

export interface SlashCommandSpec {
  name: string;
  desc: string;
  engines: SlashEngine[];
  args?: string;
}

const both = ["claude", "codex"] as SlashEngine[];

// The custom engine runs through the codex binary, so it speaks every codex command.
const withCustom = (c: SlashCommandSpec): SlashCommandSpec =>
  c.engines.includes("codex") ? { ...c, engines: [...c.engines, "custom"] } : c;

// Curated from the public Claude Code commands reference and Codex CLI/IDE slash
// command references. AgentNet-local commands are included where this surface owns
// the behavior instead of the native CLI.
export const CHAT_SLASH_COMMANDS: SlashCommandSpec[] = ([
  { name: "login", desc: "sign in to the active engine", engines: both, args: "[code]" },
  { name: "logout", desc: "sign out of the active engine", engines: both },
  { name: "new", desc: "start a fresh chat", engines: both },
  { name: "clear", desc: "clear context and start fresh", engines: both, args: "[name]" },
  { name: "compact", desc: "summarize the conversation to free context", engines: both, args: "[instructions]" },
  { name: "status", desc: "show session, model, context, and account status", engines: both },
  { name: "resume", desc: "resume a saved conversation", engines: both, args: "[session]" },
  { name: "diff", desc: "show working-tree changes", engines: ["claude", "codex"] },
  { name: "permissions", desc: "manage tool permission rules", engines: both, args: "[mode]" },
  { name: "init", desc: "create project instructions", engines: both },
  { name: "review", desc: "review local changes or a PR", engines: both, args: "[target]" },
  { name: "mcp", desc: "manage or list MCP servers", engines: both, args: "[subcommand]" },
  { name: "skills", desc: "list or refresh available skills", engines: both },
  { name: "usage", desc: "show usage, limits, or token activity", engines: both },
  { name: "cost", desc: "alias for usage/status", engines: both },
  { name: "stats", desc: "alias for usage", engines: ["claude"] },
  { name: "copy", desc: "copy the latest assistant response", engines: both, args: "[N]" },
  { name: "engine", desc: "switch AgentNet engine", engines: both, args: "claude|codex" },
  { name: "model", desc: "switch the active model", engines: both, args: "[model]" },
  { name: "mode", desc: "change AgentNet permission mode", engines: both, args: "[mode]" },
  { name: "effort", desc: "set reasoning effort", engines: both, args: "[level]" },
  { name: "help", desc: "show slash commands", engines: both },

  // Claude Code commands and bundled skills.
  { name: "add-dir", desc: "grant file access to another directory", engines: ["claude"], args: "<path>" },
  { name: "advisor", desc: "enable or disable advisor model guidance", engines: ["claude"], args: "[model|off]" },
  { name: "agents", desc: "manage agent configurations and background agents", engines: ["claude"] },
  { name: "autofix-pr", desc: "start a cloud session to fix PR feedback", engines: ["claude"], args: "[prompt]" },
  { name: "background", desc: "detach the current session to keep running", engines: ["claude"], args: "[prompt]" },
  { name: "batch", desc: "orchestrate large changes across worktrees", engines: ["claude"], args: "<instruction>" },
  { name: "branch", desc: "fork the conversation into a branch", engines: ["claude"], args: "[name]" },
  { name: "btw", desc: "ask a side question without bloating history", engines: both, args: "<question>" },
  { name: "cd", desc: "move the session to another working directory", engines: ["claude"], args: "<path>" },
  { name: "chrome", desc: "configure Claude Chrome integration", engines: ["claude"] },
  { name: "claude-api", desc: "load Claude API guidance or migration help", engines: ["claude"], args: "[migrate|managed-agents-onboard]" },
  { name: "code-review", desc: "review changes and optionally apply fixes", engines: ["claude"], args: "[effort] [--fix] [target]" },
  { name: "color", desc: "set the prompt bar color", engines: ["claude"], args: "[color|default]" },
  { name: "config", desc: "open or update Claude settings", engines: ["claude"], args: "[key=value ...]" },
  { name: "context", desc: "visualize current context usage", engines: ["claude"], args: "[all]" },
  { name: "debug", desc: "enable debug logging and diagnose an issue", engines: ["claude"], args: "[description]" },
  { name: "deep-research", desc: "run a cited multi-search research workflow", engines: ["claude"], args: "<question>" },
  { name: "desktop", desc: "continue in Claude Code Desktop", engines: ["claude"] },
  { name: "doctor", desc: "diagnose installation and runtime issues", engines: ["claude"] },
  { name: "exit", desc: "exit or detach the native CLI session", engines: both },
  { name: "export", desc: "export the conversation as text", engines: ["claude"], args: "[filename]" },
  { name: "fast", desc: "toggle fast mode when available", engines: both, args: "[on|off|status]" },
  { name: "feedback", desc: "send feedback with optional logs", engines: both, args: "[report]" },
  { name: "fewer-permission-prompts", desc: "suggest permission allowlist rules", engines: ["claude"] },
  { name: "focus", desc: "toggle Claude focus view", engines: ["claude"] },
  { name: "fork", desc: "fork work into a subagent or new thread", engines: both, args: "<directive>" },
  { name: "goal", desc: "set, view, pause, resume, or clear a goal", engines: both, args: "[condition|clear]" },
  { name: "heapdump", desc: "write a heap snapshot for diagnostics", engines: ["claude"] },
  { name: "hooks", desc: "view and manage lifecycle hooks", engines: both },
  { name: "ide", desc: "manage IDE integration or include IDE context", engines: both },
  { name: "insights", desc: "generate a Claude Code usage report", engines: ["claude"] },
  { name: "install-github-app", desc: "set up Claude GitHub Actions", engines: ["claude"] },
  { name: "install-slack-app", desc: "install the Claude Slack app", engines: ["claude"] },
  { name: "keybindings", desc: "open Claude keybindings", engines: ["claude"] },
  { name: "loop", desc: "run a prompt repeatedly", engines: ["claude"], args: "[interval] [prompt]" },
  { name: "memory", desc: "edit Claude memory files", engines: ["claude"] },
  { name: "mobile", desc: "show mobile app QR code", engines: ["claude"] },
  { name: "passes", desc: "share a free Claude Code week if eligible", engines: ["claude"] },
  { name: "plan", desc: "enter plan mode", engines: both, args: "[description]" },
  { name: "plugin", desc: "manage Claude plugins", engines: ["claude"], args: "[subcommand]" },
  { name: "powerup", desc: "open Claude Code feature lessons", engines: ["claude"] },
  { name: "privacy-settings", desc: "view privacy settings", engines: ["claude"] },
  { name: "radio", desc: "open Claude FM", engines: ["claude"] },
  { name: "recap", desc: "generate a one-line session recap", engines: ["claude"] },
  { name: "release-notes", desc: "view Claude Code release notes", engines: ["claude"] },
  { name: "reload-plugins", desc: "reload active plugins", engines: ["claude"], args: "[--force]" },
  { name: "reload-skills", desc: "rescan skills and command directories", engines: ["claude"] },
  { name: "remote-control", desc: "enable remote control", engines: ["claude"] },
  { name: "remote-env", desc: "choose cloud agent environment", engines: ["claude"] },
  { name: "rename", desc: "rename the current session", engines: ["claude"], args: "[name]" },
  { name: "rewind", desc: "rewind to a checkpoint", engines: ["claude"] },
  { name: "run", desc: "launch and inspect your app", engines: ["claude"] },
  { name: "run-skill-generator", desc: "teach /run and /verify how to run this app", engines: ["claude"] },
  { name: "sandbox", desc: "toggle Claude sandbox mode", engines: ["claude"] },
  { name: "schedule", desc: "create or manage routines", engines: ["claude"], args: "[description]" },
  { name: "security-review", desc: "review pending changes for security risks", engines: ["claude"] },
  { name: "setup-bedrock", desc: "configure Amazon Bedrock auth", engines: ["claude"] },
  { name: "setup-vertex", desc: "configure Google Vertex auth", engines: ["claude"] },
  { name: "simplify", desc: "review and simplify changed code", engines: ["claude"], args: "[target]" },
  { name: "statusline", desc: "configure status line fields", engines: both },
  { name: "stickers", desc: "order Claude Code stickers", engines: ["claude"] },
  { name: "stop", desc: "stop background work", engines: both },
  { name: "tasks", desc: "view background tasks", engines: ["claude"] },
  { name: "team-onboarding", desc: "generate a team onboarding guide", engines: ["claude"] },
  { name: "teleport", desc: "pull a web session into terminal", engines: ["claude"] },
  { name: "terminal-setup", desc: "configure terminal keybindings", engines: ["claude"] },
  { name: "theme", desc: "choose a theme", engines: both },
  { name: "tui", desc: "switch Claude terminal renderer", engines: ["claude"], args: "[default|fullscreen]" },
  { name: "ultraplan", desc: "draft an ultra plan", engines: ["claude"], args: "<prompt>" },
  { name: "ultrareview", desc: "run a deep cloud review", engines: ["claude"], args: "[PR]" },
  { name: "upgrade", desc: "open Claude plan upgrade", engines: ["claude"] },
  { name: "usage-credits", desc: "configure Claude usage credits", engines: ["claude"] },
  { name: "verify", desc: "verify an app change by running it", engines: ["claude"] },
  { name: "voice", desc: "toggle Claude voice dictation", engines: ["claude"], args: "[hold|tap|off]" },
  { name: "web-setup", desc: "connect GitHub for Claude Code web", engines: ["claude"] },
  { name: "workflows", desc: "view workflow progress", engines: ["claude"] },

  // Codex CLI and IDE extension commands.
  { name: "auto-context", desc: "toggle IDE auto context", engines: ["codex"] },
  { name: "cloud", desc: "switch to Codex cloud mode", engines: ["codex"] },
  { name: "cloud-environment", desc: "choose Codex cloud environment", engines: ["codex"] },
  { name: "local", desc: "switch to local Codex mode", engines: ["codex"] },
  { name: "keymap", desc: "remap TUI shortcuts", engines: ["codex"] },
  { name: "vim", desc: "toggle Vim composer mode", engines: ["codex"] },
  { name: "sandbox-add-read-dir", desc: "grant sandbox read access to a directory", engines: ["codex"], args: "<path>" },
  { name: "agent", desc: "switch active agent thread", engines: ["codex"] },
  { name: "apps", desc: "browse app connectors", engines: ["codex"] },
  { name: "plugins", desc: "browse installed and discoverable plugins", engines: ["codex"] },
  { name: "archive", desc: "archive the current Codex session", engines: ["codex"] },
  { name: "delete", desc: "delete the current Codex session", engines: ["codex"] },
  { name: "experimental", desc: "toggle experimental Codex features", engines: ["codex"] },
  { name: "approve", desc: "approve one retry of an auto-review denial", engines: ["codex"] },
  { name: "memories", desc: "configure Codex memories", engines: ["codex"] },
  { name: "import", desc: "import external agent configuration", engines: ["codex"] },
  { name: "mention", desc: "attach a file or folder to the conversation", engines: ["codex"], args: "<path>" },
  { name: "personality", desc: "choose Codex response style", engines: ["codex"] },
  { name: "ps", desc: "show background terminals", engines: ["codex"] },
  { name: "side", desc: "start an ephemeral side conversation", engines: ["codex"], args: "<question>" },
  { name: "raw", desc: "toggle raw scrollback mode", engines: ["codex"] },
  { name: "quit", desc: "exit the native CLI session", engines: ["codex"] },
  { name: "debug-config", desc: "inspect Codex config layers", engines: ["codex"] },
  { name: "title", desc: "configure terminal title fields", engines: ["codex"] },
] as SlashCommandSpec[]).map(withCustom);
